In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/customer.csv')

In [6]:
df.sample(5)

    age  gender   review education purchased
9    74    Male     Good        UG       Yes
15   75    Male     Poor        UG        No
33   89  Female     Good        PG       Yes
13   57  Female  Average    School        No
35   74    Male     Poor    School       Yes

In [7]:
df = df.iloc[:,2:]

In [11]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=0)

In [19]:
X_train.shape

(40, 2)

In [23]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train_encoded=oe.transform(X_train)
X_test_encoded=oe.transform(X_test)

In [28]:
X_train.head()

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

In [ ]:
X_train_encoded

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [26]:
X_train_encoded = pd.DataFrame(X_train_encoded,columns=X_train.columns)
X_test_encoded = pd.DataFrame(X_test_encoded,columns=X_test.columns)

In [29]:
X_train_encoded.head()

   review  education
0     2.0        2.0
1     0.0        0.0
2     0.0        2.0
3     1.0        0.0
4     2.0        0.0

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [31]:
le.fit(y_train)
y_train_encoded=le.transform(y_train)
y_test_encoded=le.transform(y_test)

In [34]:
y_train.head()

33    Yes
35    Yes
26     No
34     No
18     No
Name: purchased, dtype: object

In [32]:
y_train_encoded

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])